// Character utilities + streak-aware variant picker.
// The actual VARIANTS array and particle math live in their own files
// (celebration-variants.ts and particle-trajectories.ts) so they can be
// regenerated by Claude Design without disrupting business logic.

import { VARIANTS, type CelebrationVariant } from "./celebration-variants";

export type {
  CelebrationVariant,
  ParticlePattern,
  EmojiKind,
} from "./celebration-variants";
export { VARIANTS } from "./celebration-variants";
export { trajectory } from "./particle-trajectories";
export type { Waypoint } from "./particle-trajectories";

export type CharacterId = "cat" | "bunny" | "frog" | "owl" | "bear";

export const CHARACTERS: CharacterId[] = [
  "cat",
  "bunny",
  "frog",
  "owl",
  "bear",
];

/** Deterministic character pick per lesson — same lesson always gets the same buddy. */
export function pickCharacterForLesson(lessonId: string): CharacterId {
  let h = 0;
  for (let i = 0; i < lessonId.length; i++) {
    h = (h << 5) - h + lessonId.charCodeAt(i);
    h |= 0;
  }
  return CHARACTERS[Math.abs(h) % CHARACTERS.length];
}

const COMMON = VARIANTS.filter((v) => !v.rare);
const RARE = VARIANTS.filter((v) => v.rare);

/** Picks a celebration variant. Rare ones only enter the pool at streak ≥ 3. */
export function pickVariant(streak: number): CelebrationVariant {
  const rareChance = streak >= 5 ? 0.5 : streak >= 3 ? 0.25 : 0;
  if (Math.random() < rareChance) {
    return RARE[Math.floor(Math.random() * RARE.length)];
  }
  return COMMON[Math.floor(Math.random() * COMMON.length)];
}
